### ISSUE TITLE
days-till-holiday and days-till-birthday

### ISSUE THREAD

**Issue by LimesKey** [inspectorrex/discordtimestamp#1]
Please add the days till Christmas option so I can count how many days there are till Christmas. Also extend this for other holidays like Thanksgiving and Easter, etc.

Another great idea would be the days and months till birthday option, I know discord does not support dynamic timestamps but the user would input their birthday without the year so just the month and date and it puts days and months till next birthday.

**Comment by inspectorrex** [comment]
I might beable to add some Chips under the Date Selection to allow to Quickly Select Import Dates of Major World Events, like Christmas and Holdays

i don't think however that adding a birthday option is viable since you would have to still enter the date yourself

**Comment by LimesKey** [comment]
> i don't think however that adding a birthday option is viable since you would have to still enter the date yourself

At least make it so you won't have to enter the year for your birthdate.

**Comment by LimesKey** [comment]
@inspectorrex 
### Holidays to include:

Easter, Thanksgiving, Christmas, Valentine's Day, St. Patrick's Day, Cinco De Mayo (D), Mother's Day, Father's Day, First Day of Pride Month (D), Columbus Day (D), Halloween, Election Day (D), Black Friday (D), New Year's Eve, Independence Day (D),

Items associated with the "D" label are to be considered dynamic, in a sense that the option to select that holiday will only be shown 2 weeks before the holiday is to occur.

**Comment by inspectorrex** [comment]
Will be fully added within the next couple days, thank you :D
