### ISSUE TITLE
Fetch QuickSelection dates from Google Calender's API

### ISSUE THREAD

**Issue by LimesKey** [inspectorrex/discordtimestamp#2]
Google Calendar has a feature that shows public holidays in your native country, an example would be, "Holidays in Canada"
![image](https://user-images.githubusercontent.com/85136735/215301594-00b16d42-88a1-48e9-9f33-f8eb92ae5944.png)

Some documentation for this API is located [here](https://github.com/googleworkspace/browser-samples/blob/main/calendar/quickstart/index.html). This would prevent having hard-coded dates and allow new holidays to be instantly added automatically. A future feature could involve also fetching from the user's private Google Calendar too.

**Comment by LimesKey** [comment]
The API request should be made out server-side and be cached for better performance.

**Comment by inspectorrex** [comment]
Checking the Url Provided brings me to a Google Calendar Api which doesn't contain public Holiday Data...

Cloud you please provide more resources

**Comment by LimesKey** [comment]
@inspectorrex, you are a very smart boy with a big brain and are very capable of doing this yourself. I know you are a strong person that can achieve very much in life. In case you have trouble with this task, I have provided some more resources below. Well wishes, I hope this message finds you well.

```html
<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FToronto&src=ZW4uY2FuYWRpYW4jaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%230B8043" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```
```javascript
const BASE_CALENDAR_URL = "https://www.googleapis.com/calendar/v3/calendars";
const BASE_CALENDAR_ID_FOR_PUBLIC_HOLIDAY =
  "holiday@group.v.calendar.google.com"; // Calendar Id. This is public but apparently not documented anywhere officialy.
const API_KEY = "YOUR_API_KEY";
const CALENDAR_REGION = "en.usa"; // This variable refers to region whose holidays 
```
https://dev.to/monfernape/get-country-holidays-using-google-calendar-api-3dh6
